name: Update Meta IP YAML

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert
        run: |
          chmod +x convert.sh
          ./convert.sh

      - name: Commit and push
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add meta.yaml
          git commit -m "update meta ip" || echo "no changes"
          git push
